### ISSUE TITLE
Product images aren't syncing. 

### ISSUE THREAD

**Issue by nicksanchezc137** [commercetools/commercetools-project-sync#566] opened 2024-03-19 06:36 UTC
All the product data looks fine other than variant images. That doesn't seem to be working.

**Comment by lojzatran** [comment] 2024-03-19 19:03
Hi @nicksanchezc137 

Thank you for the issue report. I added a test for your case and it is working: https://github.com/commercetools/commercetools-project-sync/pull/567.

Can you give more details what is not working or provide a test that is failing?

Thank you.

**Comment by kkattaexp** [comment] 2024-03-21 02:12
I am having the same issue, when I sync from one project to another all the products and the data got synced but the images in the variants are not synced, the images in the variants are empty.

**Comment by lojzatran** [comment] 2024-03-21 09:59
Hi @kkattaexp 

I checked again and cannot reproduce the issue. Can you provide the docker command you are running and the version of the docker image?

Thank you.

**Comment by kkattaexp** [comment] 2024-03-21 13:53
`docker run \
commercetools/commercetools-project-sync:5.4.6 -s products -productQueryParameters "{\"limit\": 10, \"where\": \"lastModifiedAt > \\\"2023-01-01T08:27:47.229Z\\\" and variants(availability(availableQuantity > 0)) and masterVariant(attributes(name=\\\"itemStatus\\\" and value=true)) and key=\\\"05049450\\\" and variants(attributes(name=\\\"skuStatus\\\" and value=true)) and categories is not empty \"}"empty \"}"`

**Comment by lojzatran** [comment] 2024-03-23 08:50
Hi @kkattaexp 

Can you try again with the newest release 5.4.7? There was a bug fix with image syncing (https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#1005---feb-8-2024)

Thank you.

**Comment by andihalberkamp** [comment] 2024-03-24 21:33
Hi @lojzatran,

Thanks a lot lam, I had the same issue and I hope the bugfix will fix this
best 
Andi

**Comment by kkattaexp** [comment] 2024-03-25 20:08
Thank you @lojzatran it worked with this

**Comment by lojzatran** [comment] 2024-03-26 08:12
Thank you for your feedbacks. I‘m closing the issue. If you have any more comments, feel free to reply/reopen it.

**Closed by lojzatran** 2024-03-26 08:12 UTC
