### ISSUE TITLE
Remove unnecessary log message from FastMoney class

### ISSUE THREAD

**Issue by jeanpierrecarvalho** [commercetools/commercetools-project-sync#520] opened 2023-11-06 22:52 UTC
**Description:**

There is an unnecessary log message in the FastMoney class that should be removed

**Steps to Reproduce:**

1. Run the commercetools/commercetools-project-sync:5.4.0 docker image with the following params:

`commercetools/commercetools-project-sync:5.4.0 -s products -r sync-products -f`

2. Observe the log output, which includes the message:
"Nov 06, 2023 10:45:48 PM org.javamoney.moneta.FastMoney defaultFormat INFO: Using default formatter for toString()"

**Comment by lojzatran** [comment] 2023-11-07 09:12
Hi @jeanpierrecarvalho 

Thank you for reporting the issue.

We will check it.

**Comment by jeanpierrecarvalho** [comment] 2023-11-07 14:15
Thanks @lojzatran , let me know if you need anything else.

**Comment by lojzatran** [comment] 2024-01-09 10:51
Hi @jeanpierrecarvalho 

I tried to reproduce the issue again today with the newest version and I cannot reproduce it anymore. I'm hereby closing this ticket. Feel free to reopen if you still the the issue.

**Closed by lojzatran** 2024-01-09 10:51 UTC

**Comment by kiamesdavies** [comment] 2024-12-11 01:03
Its a version 1.4.2 thing, which is four years ago
